language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "nightly"
  allow_failures:
    - python: "nightly"
before_install:
  - pip install pytest --upgrade  # Workaround Python 3.5 not having updated PyTest package
install:
  - pip install .
script: python setup.py test