language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "nightly"
before_install:
  - pip uninstall -y pytest
  - pip install --upgrade setuptools_scm
  - pip install codecov
install:
  - pip install .
script: python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
