[tool.poetry]
name = "aiospamc"
version = "0.6.1"
description = "An asyncio-based library to communicate with SpamAssassin's SPAMD service."
authors = ["Michael Caley <mjcaley@darkarctic.com>"]
license = "MIT"
readme = "README.rst"

repository = "https://github.com/mjcaley/aiospamc"
homepage = "https://github.com/mjcaley/aiospamc"

classifiers = [
    'Development Status :: 4 - Beta',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Topic :: Communications :: Email :: Filters'
]

keywords = ["spam", "spamc", "spamassassin"]

[tool.poetry.dependencies]
python = "^3.5"
certifi = "^2020.6"

[tool.poetry.dev-dependencies]
asynctest = "^0.13.0"
pytest = "^6.0"
pytest-cov = "^2.10"
pytest-asyncio = "^0.14.0"
sphinx = "^3.1"
pytest-mock = "^3.2"
cryptography = "^3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
